------------------------------
-- CREATE PA-JARVIS DB OBJECTS
------------------------------

-- psql -U postgres -v target_db="pa-jarvis-dev" -v pgsql_user="pa_jarvis_app_dev" -f "C:\apinc\pgsql\pa-jarvis-db-create.sql"
-- psql -U postgres -v target_db="pa-jarvis-prd" -v pgsql_user="pa_jarvis_app_prd" -f "C:\apinc\pgsql\pa-jarvis-db-create.sql"


-- CONNECT TO DATABASE
\c :target_db

-- CREATE SCHEMAS

CREATE SCHEMA config;

ALTER SCHEMA config OWNER TO postgres;

GRANT USAGE ON SCHEMA config TO :pgsql_user;


CREATE SCHEMA logging;

ALTER SCHEMA logging OWNER TO postgres;

GRANT USAGE ON SCHEMA logging TO :pgsql_user;


CREATE SCHEMA toolsdata;

ALTER SCHEMA toolsdata OWNER TO postgres;

GRANT USAGE ON SCHEMA toolsdata TO :pgsql_user;


-- CREATE CONFIG TABLES

CREATE TABLE IF NOT EXISTS config.agents
(
    agent_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    agent_name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    agent_description text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT agents_pkey PRIMARY KEY (agent_id),
    CONSTRAINT agents_agent_name_key UNIQUE (agent_name)
);

ALTER TABLE IF EXISTS config.agents OWNER to postgres;

GRANT ALL ON TABLE config.agents TO :pgsql_user;

GRANT ALL ON TABLE config.agents TO postgres;


CREATE TABLE IF NOT EXISTS config.llm_system_instructions
(
    instrc_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    instrc_type character varying(100) COLLATE pg_catalog."default" NOT NULL,
    instruction text COLLATE pg_catalog."default" NOT NULL,
    instrc_priority bigint,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    agent_id bigint,
    CONSTRAINT llm_system_instructions_pkey PRIMARY KEY (instrc_id)
);

ALTER TABLE IF EXISTS config.llm_system_instructions OWNER to postgres;

GRANT ALL ON TABLE config.llm_system_instructions TO :pgsql_user;

GRANT ALL ON TABLE config.llm_system_instructions TO postgres;


CREATE TABLE IF NOT EXISTS config.tools_registry
(
    tool_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    tool_name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    tool_description text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    agent_id bigint,
    CONSTRAINT tools_registry_pkey PRIMARY KEY (tool_id),
    CONSTRAINT tools_registry_tool_name_key UNIQUE (tool_name),
    CONSTRAINT tools_registry_agent_id_fkey FOREIGN KEY (agent_id)
        REFERENCES config.agents (agent_id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE SET NULL
);

ALTER TABLE IF EXISTS config.tools_registry OWNER to postgres;

GRANT ALL ON TABLE config.tools_registry TO :pgsql_user;

GRANT ALL ON TABLE config.tools_registry TO postgres;


CREATE TABLE IF NOT EXISTS config.tools_parameters
(
    param_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    tool_id bigint,
    param_name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    param_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    param_description text COLLATE pg_catalog."default" NOT NULL,
    is_required boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT tool_parameters_pkey PRIMARY KEY (param_id),
    CONSTRAINT tool_parameters_tool_id_param_name_key UNIQUE (tool_id, param_name),
    CONSTRAINT tool_parameters_tool_id_fkey FOREIGN KEY (tool_id)
        REFERENCES config.tools_registry (tool_id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

ALTER TABLE IF EXISTS config.tools_parameters OWNER to postgres;

GRANT ALL ON TABLE config.tools_parameters TO :pgsql_user;

GRANT ALL ON TABLE config.tools_parameters TO postgres;


-- CREATE LOGGING TABLES

CREATE TABLE IF NOT EXISTS logging.llm_calls
(
    llm_call_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    request_id uuid NOT NULL,
    calling_agent_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    message_sent text COLLATE pg_catalog."default" NOT NULL,
    message_response text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT llm_calls_pkey PRIMARY KEY (llm_call_id)
);

ALTER TABLE IF EXISTS logging.llm_calls OWNER to postgres;

GRANT ALL ON TABLE logging.llm_calls TO :pgsql_user;

GRANT ALL ON TABLE logging.llm_calls TO postgres;


CREATE TABLE IF NOT EXISTS logging.tool_calls
(
    tool_call_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    request_id uuid NOT NULL,
    calling_agent_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    tool_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    tool_arguments text COLLATE pg_catalog."default",
    tool_output text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT tool_calls_pkey PRIMARY KEY (tool_call_id)
);

ALTER TABLE IF EXISTS logging.tool_calls OWNER to postgres;

GRANT ALL ON TABLE logging.tool_calls TO :pgsql_user;

GRANT ALL ON TABLE logging.tool_calls TO postgres;


CREATE TABLE IF NOT EXISTS logging.service_events
(
    event_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    request_id uuid NOT NULL,
    service_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    script_name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    event_type character varying(100) COLLATE pg_catalog."default" NOT NULL,
    chat_message text COLLATE pg_catalog."default" NOT NULL,
    chat_history text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT service_events_pkey PRIMARY KEY (event_id)
);

ALTER TABLE IF EXISTS logging.service_events OWNER to postgres;

GRANT ALL ON TABLE logging.service_events TO :pgsql_user;

GRANT ALL ON TABLE logging.service_events TO postgres;


-- CREATE TOOLS DATA TABLES

CREATE TABLE toolsdata.gdrive_folders (
    folder_id character varying(200) NOT NULL,
    folder_name character varying(200) NOT NULL,
    folder_description text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

ALTER TABLE IF EXISTS toolsdata.gdrive_folders OWNER to postgres;

GRANT ALL ON TABLE toolsdata.gdrive_folders TO :pgsql_user;

GRANT ALL ON TABLE toolsdata.gdrive_folders TO postgres;


CREATE TABLE IF NOT EXISTS toolsdata.task_list
(
    task_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    task_name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    task_description text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT task_pkey PRIMARY KEY (task_id),
    CONSTRAINT task_name_key UNIQUE (task_name)
);

ALTER TABLE IF EXISTS toolsdata.task_list OWNER to postgres;

GRANT ALL ON TABLE toolsdata.task_list TO :pgsql_user;

GRANT ALL ON TABLE toolsdata.task_list TO postgres;


CREATE TABLE IF NOT EXISTS toolsdata.shopping_list
(
    item_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    item_name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    item_description text COLLATE pg_catalog."default",
    item_priority character varying(10) COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT item_pkey PRIMARY KEY (item_id),
    CONSTRAINT item_name_key UNIQUE (item_name)
);

ALTER TABLE IF EXISTS toolsdata.shopping_list OWNER to postgres;

GRANT ALL ON TABLE toolsdata.shopping_list TO :pgsql_user;

GRANT ALL ON TABLE toolsdata.shopping_list TO postgres;