traefikIngress:
  host: dev.chat.arushparulinc.com
  entryPoint: web
  tls:
    enabled: false
    certResolver: ""

devUpstream:
  enabled: false
  host: dev.chat.arushparulinc.com
  ip: ""
  port: 80

frontend:
  njsEnv: " - DEV"
  image:
    repository: ghcr.io/arushparulinc/pa-jarvis-frontend
    tag: sha-0f5610271dc46aec528d70302a8bc7d6cf5baf7f
    pullPolicy: IfNotPresent

backend:
  image:
    repository: ghcr.io/arushparulinc/pa-jarvis-backend
    tag: sha-0f5610271dc46aec528d70302a8bc7d6cf5baf7f
    pullPolicy: IfNotPresent

agents:
  image:
    repository: ghcr.io/arushparulinc/pa-jarvis-agents
    tag: sha-0f5610271dc46aec528d70302a8bc7d6cf5baf7f
    pullPolicy: IfNotPresent

llm:
  image:
    repository: ghcr.io/arushparulinc/pa-jarvis-llm
    tag: sha-0f5610271dc46aec528d70302a8bc7d6cf5baf7f
    pullPolicy: IfNotPresent

tools:
  image:
    repository: ghcr.io/arushparulinc/pa-jarvis-tools
    tag: sha-0f5610271dc46aec528d70302a8bc7d6cf5baf7f
    pullPolicy: IfNotPresent

storage:
  image:
    repository: ghcr.io/arushparulinc/pa-jarvis-storage
    tag: sha-0f5610271dc46aec528d70302a8bc7d6cf5baf7f
    pullPolicy: IfNotPresent

scripts:
  image:
    repository: ghcr.io/arushparulinc/pa-jarvis-scripts
    tag: sha-0f5610271dc46aec528d70302a8bc7d6cf5baf7f
    pullPolicy: IfNotPresent
