traefikIngress:
  host: chat.arushparulinc.com
  entryPoint: websecure
  tls:
    enabled: true
    certResolver: letsencrypt

devUpstream:
  enabled: true
  host: dev.chat.arushparulinc.com
  ip: "192.168.0.10"
  port: 80

frontend:
  njsEnv: ""
  image:
    repository: ghcr.io/arushparulinc/pa-jarvis-frontend
    tag: sha-ab85d51f0fa5c44d50b371437adc6a4b41aa91fd
    pullPolicy: IfNotPresent

backend:
  image:
    repository: ghcr.io/arushparulinc/pa-jarvis-backend
    tag: sha-ab85d51f0fa5c44d50b371437adc6a4b41aa91fd
    pullPolicy: IfNotPresent

agents:
  image:
    repository: ghcr.io/arushparulinc/pa-jarvis-agents
    tag: sha-ab85d51f0fa5c44d50b371437adc6a4b41aa91fd
    pullPolicy: IfNotPresent

llm:
  image:
    repository: ghcr.io/arushparulinc/pa-jarvis-llm
    tag: sha-ab85d51f0fa5c44d50b371437adc6a4b41aa91fd
    pullPolicy: IfNotPresent

tools:
  image:
    repository: ghcr.io/arushparulinc/pa-jarvis-tools
    tag: sha-ab85d51f0fa5c44d50b371437adc6a4b41aa91fd
    pullPolicy: IfNotPresent

storage:
  image:
    repository: ghcr.io/arushparulinc/pa-jarvis-storage
    tag: sha-ab85d51f0fa5c44d50b371437adc6a4b41aa91fd
    pullPolicy: IfNotPresent

scripts:
  image:
    repository: ghcr.io/arushparulinc/pa-jarvis-scripts
    tag: sha-ab85d51f0fa5c44d50b371437adc6a4b41aa91fd
    pullPolicy: IfNotPresent

analytics:
  host: dashboard.arushparulinc.com
  image:
    repository: ghcr.io/arushparulinc/pa-jarvis-analytics
    tag: sha-ab85d51f0fa5c44d50b371437adc6a4b41aa91fd
    pullPolicy: IfNotPresent
