traefikIngress:
  host: dev.chat.arushparulinc.com

frontend:
  image:
    repository: ghcr.io/arushparulinc/pa-jarvis-frontend
    tag: sha-393e1d2b85704792445f014d7da33d03f0664508
    pullPolicy: IfNotPresent

backend:
  image:
    repository: ghcr.io/arushparulinc/pa-jarvis-backend
    tag: sha-393e1d2b85704792445f014d7da33d03f0664508
    pullPolicy: IfNotPresent

agents:
  image:
    repository: ghcr.io/arushparulinc/pa-jarvis-agents
    tag: sha-393e1d2b85704792445f014d7da33d03f0664508
    pullPolicy: IfNotPresent

llm:
  image:
    repository: ghcr.io/arushparulinc/pa-jarvis-llm
    tag: sha-393e1d2b85704792445f014d7da33d03f0664508
    pullPolicy: IfNotPresent

tools:
  image:
    repository: ghcr.io/arushparulinc/pa-jarvis-tools
    tag: sha-393e1d2b85704792445f014d7da33d03f0664508
    pullPolicy: IfNotPresent

storage:
  image:
    repository: ghcr.io/arushparulinc/pa-jarvis-storage
    tag: sha-393e1d2b85704792445f014d7da33d03f0664508
    pullPolicy: IfNotPresent
