apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd

data:
  resource.exclusions: |
    # Network resources created by Kubernetes
    - apiGroups:
        - ""
      kinds:
        - Endpoints

    # Internal Kubernetes coordination resources
    - apiGroups:
        - coordination.k8s.io
      kinds:
        - Lease

    # Internal authentication and authorization resources
    - apiGroups:
        - authentication.k8s.io
        - authorization.k8s.io
      kinds:
        - SelfSubjectReview
        - TokenReview
        - LocalSubjectAccessReview
        - SelfSubjectAccessReview
        - SelfSubjectRulesReview
        - SubjectAccessReview

    # Intermediate certificate requests
    - apiGroups:
        - certificates.k8s.io
      kinds:
        - CertificateSigningRequest

    - apiGroups:
        - cert-manager.io
      kinds:
        - CertificateRequest

    # Cilium internal resources
    - apiGroups:
        - cilium.io
      kinds:
        - CiliumIdentity
        - CiliumEndpoint
        - CiliumEndpointSlice

    # Kyverno reporting resources
    - apiGroups:
        - kyverno.io
        - reports.kyverno.io
        - wgpolicyk8s.io
      kinds:
        - PolicyReport
        - ClusterPolicyReport
        - EphemeralReport
        - ClusterEphemeralReport
        - AdmissionReport
        - ClusterAdmissionReport
        - BackgroundScanReport
        - ClusterBackgroundScanReport
        - UpdateRequest