apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm
  template:
    metadata:
      labels:
        app: llm
    spec:
      containers:
        - name: llm
          image: "{{ .Values.llm.image.repository }}:{{ .Values.llm.image.tag }}"
          imagePullPolicy: {{ .Values.llm.image.pullPolicy }}

          ports:
            - containerPort: 8002

          env:
            - name: STORAGE_SERVICE_URL
              value: "http://storage:8004"
            - name: OLLAMA_HOST
              value: "http://192.168.0.30:11434"
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: llm-secrets
                  key: GEMINI_API_KEY
          envFrom:
            - secretRef:
                name: storage-db-secrets
