apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm
  template:
    metadata:
      labels:
        app: llm
    spec:
      containers:
        - name: llm
          image: 02source-llm:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8002

          env:
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: llm-secrets
                  key: GEMINI_API_KEY