apiVersion: apps/v1
kind: Deployment
metadata:
  name: tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tools
  template:
    metadata:
      labels:
        app: tools
    spec:
      containers:
        - name: tools
          image: "{{ .Values.tools.image.repository }}:{{ .Values.tools.image.tag }}"
          imagePullPolicy: {{ .Values.tools.image.pullPolicy }}
          ports:
            - containerPort: 8003
          env:
            - name: STORAGE_SERVICE_URL
              value: "http://storage:8004"
