apiVersion: apps/v1
kind: Deployment
metadata:
  name: tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tools
  template:
    metadata:
      labels:
        app: tools
    spec:
      containers:
        - name: tools
          image: 02source-tools:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8003