apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: revproxy
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt

spec:
  ingressClassName: traefik

  tls:
    - hosts:
        - {{ .Values.traefikIngress.host | quote }}

  rules:
    - host: {{ .Values.traefikIngress.host | quote }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8000

          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
