apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: revproxy
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: {{ .Values.traefikIngress.entryPoint | quote }}
{{ if .Values.traefikIngress.tls.enabled }}
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: {{ .Values.traefikIngress.tls.certResolver | quote }}
{{ end }}

spec:
  ingressClassName: traefik

{{ if .Values.traefikIngress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.traefikIngress.host | quote }}
{{ end }}

  rules:
    - host: {{ .Values.traefikIngress.host | quote }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8000

          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80

{{ if .Values.devUpstream.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: dev-upstream-traefik
  annotations:
    traefik.ingress.kubernetes.io/service.passhostheader: "true"
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: {{ .Values.devUpstream.port }}

---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: dev-upstream-traefik-1
  labels:
    kubernetes.io/service-name: dev-upstream-traefik
    endpointslice.kubernetes.io/managed-by: pa-jarvis-helm
addressType: IPv4
ports:
  - name: http
    appProtocol: http
    protocol: TCP
    port: {{ .Values.devUpstream.port }}
endpoints:
  - addresses:
      - {{ required "devUpstream.ip must be configured" .Values.devUpstream.ip | quote }}
    conditions:
      ready: true

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-forward
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: {{ .Values.traefikIngress.tls.certResolver | quote }}
spec:
  ingressClassName: traefik

  tls:
    - hosts:
        - {{ .Values.devUpstream.host | quote }}

  rules:
    - host: {{ .Values.devUpstream.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dev-upstream-traefik
                port:
                  number: 80
{{ end }}