services:
  frontend:
    build:
      context: ./Frontend/njs_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./Backend/fastpy_backend
    ports:
      - "8000:8000"
    env_file:
      - ./Backend/fastpy_backend/.env
    environment:
      MASTER_AGENT_URL: http://agents:8001
      STORAGE_SERVICE_URL: http://storage:8004
    depends_on:
      - agents
      - storage

  agents:
    build:
      context: ./Agents
    ports:
      - "8001:8001"
    env_file:
      - ./Agents/.env
    environment:
      LLM_SERVICE_URL: http://llm:8002
      TOOLS_SERVICE_URL: http://tools:8003
      STORAGE_SERVICE_URL: http://storage:8004
    depends_on:
      - llm
      - tools
      - storage

  llm:
    build:
      context: ./LLM
    ports:
      - "8002:8002"
    env_file:
      - ./LLM/.env
    environment:
      OLLAMA_HOST: http://192.168.0.30:11434
      STORAGE_SERVICE_URL: http://storage:8004
    depends_on:
      - storage

  tools:
    build:
      context: ./Tools
    ports:
      - "8003:8003"
    env_file:
      - ./Tools/.env
    environment:
      STORAGE_SERVICE_URL: http://storage:8004
      GOOGLE_APPLICATION_CREDENTIALS: /app/secrets/service-account.json
    volumes:
      - ./Tools/credentials/service-account.json:/app/secrets/service-account.json:ro
    depends_on:
      - storage

  storage:
    build:
      context: ./Storage
    ports:
      - "8004:8004"
    env_file:
      - ./Storage/.env
